require "rb_sys/extensiontask"

GEMSPEC = Gem::Specification.load("outpunch.gemspec")

RbSys::ExtensionTask.new("outpunch", GEMSPEC) do |ext|
  ext.lib_dir = "lib/outpunch"
end

task default: :compile
