/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class OutpunchConnection {
  pushMessage(text: string): Promise<void>
  onMessage(callback: (err: null, msg: string) => void): void
  close(): void
  run(): Promise<void>
}

export declare class OutpunchServer {
  constructor(config: ServerConfig)
  createConnection(): OutpunchConnection
  handleRequest(request: IncomingRequest): Promise<TunnelResponse>
}

export interface IncomingRequest {
  service: string
  method: string
  path: string
  query?: Record<string, string>
  headers?: Record<string, string>
  body?: string
}

export interface ServerConfig {
  secret: string
  timeoutMs?: number
  maxBodySize?: number
}

export interface TunnelResponse {
  requestId: string
  status: number
  headers: Record<string, string>
  body?: string
  bodyEncoding?: string
}
