
default:
	@just --list

build:
	npx napi build --platform --release

build-debug:
	npx napi build --platform

test: build-debug
	npx vitest run

test-verbose: build-debug
	npx vitest run --reporter=verbose
